name: "Install Python dependencies"
description: "Install Python dependencies"

runs:
  using: "composite"
  steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Clone python-greetings
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Installing dependencies via pip
      run: pip install -r requirements.txt
      shell: cmd
      working-directory: python-greetings
