name: Python Greetings Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: ./.github/actions/install-deps

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Deploy to dev environment
        uses: ./.github/actions/deploy
        with:
          env: dev
          port: 7001

  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - name: Force cleanup locked folder
        shell: cmd
        run: |
          pm2 kill
          timeout /t 5 /nobreak >nul
          rmdir /s /q "C:\actions-runner\_work\python-pipeline\python-pipeline\python-greetings" || echo Folder removal failed
      - name: Run tests on dev environment
        uses: ./.github/actions/test
        with:
          env: dev

  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - name: Deploy to staging environment
        uses: ./.github/actions/deploy
        with:
          env: staging
          port: 7002

  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - name: Run tests on staging environment
        uses: ./.github/actions/test
        with:
          env: staging

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - name: Deploy to preprod environment
        uses: ./.github/actions/deploy
        with:
          env: preprod
          port: 7003

  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - name: Run tests on preprod environment
        uses: ./.github/actions/test
        with:
          env: preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - name: Deploy to prod environment
        uses: ./.github/actions/deploy
        with:
          env: prod
          port: 7004

  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - name: Run tests on prod environment
        uses: ./.github/actions/test
        with:
          env: prod
